import { Keymapping } from './index';
import { LANGS } from "../Langs";

// This mapping is typically used in Windows 10 and Linux by default
class UsMapping extends Keymapping {
    constructor() {
        super()
        this.name = LANGS.FinnishStandardKeyboard
        this.mapping = {
            "KC_ESCAPE" : { text: "Esc" },
            "KC_F1" : { text: "F1" },
            "KC_F2" : { text: "F2" },
            "KC_F3" : { text: "F3" },
            "KC_F4" : { text: "F4" },
            "KC_F5" : { text: "F5" },
            "KC_F6" : { text: "F6" },
            "KC_F7" : { text: "F7" },
            "KC_F8" : { text: "F8" },
            "KC_F9" : { text: "F9" },
            "KC_F10" : { text: "F10" },
            "KC_F11" : { text: "F11" },
            "KC_F12" : { text: "F12" },
            "KC_PSCREEN" : { text: "PrtScn" },
            "KC_SCROLLLOCK" : { text: "Scroll Lock" },
            "KC_PAUSE" : { text: "Pause Break" },
            "KC_GRAVE" : "`¬",
            "KC_1" : "1!",
            "KC_2" : "2\"",
            "KC_3" : "3£",
            "KC_4" : "4$",
            "KC_5" : "5%",
            "KC_6" : "6^",
            "KC_7" : "7&",
            "KC_8" : "8*",
            "KC_9" : "9(",
            "KC_0" : "0)",
            "KC_MINUS" : "-_",
            "KC_EQUAL" : "=+",
            "KC_BSPACE" : { text: "Backspace" },
            "KC_INSERT" : { text: "Insert" },
            "KC_HOME" : { text: "Home" },
            "KC_PGUP" : { text: "PgUp" },
            "KC_NUMLOCK" : { text: "Num Lock" },
            "KC_KP_SLASH": { text: ["", "/"] },
            "KC_KP_ASTERISK": { text: ["", "*"] },
            "KC_KP_MINUS": { text: ["", "-"] },
            "KC_TAB" : { text: "Tab" },
            "KC_Q" : "qQ",
            "KC_W" : "wW",
            "KC_E" : "eE",
            "KC_R" : "rR",
            "KC_T" : "tT",
            "KC_Y" : "yY",
            "KC_U" : "uU",
            "KC_I" : "iI",
            "KC_O" : "oO",
            "KC_P" : "pP",
            "KC_LBRACKET" : "[{",
            "KC_RBRACKET" : "]}",
            "KC_ENTER" : { text: "Enter" },
            "KC_DELETE" : { text: "Delete" },
            "KC_END" : { text: "End" },
            "KC_PGDOWN" : { text: "PgDn" },
            "KC_KP_7" : { text: ["Home", "7"]},
            "KC_KP_8" : { text: ["↑", "8"]},
            "KC_KP_9" : { text: ["PgUp", "9"]},
            "KC_KP_PLUS": { text: ["", "+"] },
            "KC_CAPSLOCK" : { text: "Caps Lock" },
            "KC_A" : "aA",
            "KC_S" : "sS",
            "KC_D" : "dD",
            "KC_F" : "fF",
            "KC_G" : "gG",
            "KC_H" : "hH",
            "KC_J" : "jJ",
            "KC_K" : "kK",
            "KC_L" : "lL",
            "KC_SCOLON" : ";:",
            "KC_QUOTE" : "'@",
            "KC_NONUS_HASH" : "#~",
            "KC_KP_4" : { text: ["←", "4"]},
            "KC_KP_5" : { text: ["", "5"]},
            "KC_KP_6" : { text: ["→", "6"]},
            "KC_LSHIFT" : { text: "Shift" },
            "KC_NONUS_BSLASH" : "\\|",
            "KC_Z" : "zZ",
            "KC_X" : "xX",
            "KC_C" : "cC",
            "KC_V" : "vV",
            "KC_B" : "bB",
            "KC_N" : "nN",
            "KC_M" : "mM",
            "KC_COMMA" : ",<",
            "KC_DOT" : ".>",
            "KC_SLASH" : "/?",
            "KC_RSHIFT" : { text: "Shift" },
            "KC_UP" : { text: "↑" },
            "KC_KP_1" : { text: ["End", "1"]},
            "KC_KP_2" : { text: ["↓", "2"]},
            "KC_KP_3" : { text: ["PgDn", "3"]},
            "KC_KP_ENTER" : { text: "Enter" },
            "KC_LCTRL" : { text: "Ctrl" },
            "KC_LGUI" : { text: "Win" },
            "KC_LALT" : { text: "Alt" },
            "KC_SPACE" : { text: "" },
            "KC_RALT" : { text: "AltGr" },
            "KC_RGUI" : { text: "Win" },
            "KC_APPLICATION" : { text: "Menu" },
            "KC_RCTRL" : { text: "Ctrl" },
            "KC_LEFT" : { text: "←" },
            "KC_DOWN" : { text: "↓" },
            "KC_RIGHT" : { text: "→" },
            "KC_KP_0" : { text: ["Ins", "0"]},
            "KC_KP_DOT" : { text: ["Del", "."]}
        }
    }
}