export const exampleKeymap = {
    keyboard: "ergodox_ez",
    lang: "us",
    keymap: `
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    // First layer
    [0] = LAYOUT_ergodox(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, LGUI(KC_R), MO(1), KC_A, KC_S, KC_D, KC_F, KC_G, OSM(MOD_LSFT), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_LGUI, OSM(MOD_LCTL), KC_NONUS_BSLASH, KC_LGUI, OSM(MOD_LALT), MO(3), KC_MEDIA_PLAY_PAUSE, KC_AUDIO_MUTE, KC_TRNS, KC_SPACE, OSL(4), KC_TRNS, KC_6, KC_7, KC_8, KC_9, KC_0, KC_TRNS, KC_BSPACE, KC_TRNS, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_NONUS_HASH, KC_H, KC_J, KC_K, KC_L, KC_SCOLON, KC_QUOTE, KC_ENTER, KC_N, KC_M, KC_COMMA, KC_DOT, KC_SLASH, OSM(MOD_RSFT), MO(3), OSM(MOD_RALT), KC_APPLICATION, KC_TRNS, OSM(MOD_LCTL), KC_MEDIA_PREV_TRACK, KC_MEDIA_NEXT_TRACK, KC_TRNS, KC_TRNS, OSL(4), KC_SPACE),

    // Second layer
    [1] = LAYOUT_ergodox(KC_TRNS, LALT(LCTL(LGUI(LSFT(KC_1)))), LALT(LCTL(LGUI(LSFT(KC_2)))), LALT(LCTL(LGUI(LSFT(KC_3)))), LALT(LCTL(LGUI(LSFT(KC_4)))), LALT(LCTL(LGUI(LSFT(KC_5)))), KC_TRNS, KC_TRANSPARENT, LALT(LCTL(LGUI(LSFT(KC_Q)))), LALT(LCTL(LGUI(LSFT(KC_W)))), LALT(LCTL(LGUI(LSFT(KC_E)))), LALT(LCTL(LGUI(LSFT(KC_R)))), LALT(LCTL(LGUI(LSFT(KC_T)))), KC_TRNS, KC_TRNS, KC_TRNS, LALT(LCTL(LSFT(KC_S))), KC_LALT, KC_LSHIFT, KC_TRNS, KC_TRNS, KC_TRNS, LALT(LCTL(LGUI(LSFT(KC_X)))), LALT(LCTL(LGUI(LSFT(KC_C)))), LALT(LCTL(LGUI(LSFT(KC_V)))), LALT(LCTL(LGUI(LSFT(KC_B)))), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RGB_MOD, RGB_SLD, RGB_VAI, KC_LCTL, RGB_TOG, RGB_VAD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_DELETE, KC_HOME, KC_UP, KC_END, KC_PGUP, KC_TRNS, KC_ENTER, KC_LEFT, KC_DOWN, KC_RIGHT, KC_PGDOWN, KC_TRNS, KC_TRNS, KC_BSPACE, KC_TRNS, KC_TRNS, RGB_MODE_GRADIENT, RGB_MODE_XMAS, RGB_MODE_KNIGHT, RGB_MODE_SNAKE, RGB_MODE_SWIRL, RGB_MODE_RAINBOW, RGB_MODE_BREATHE, RGB_MODE_PLAIN, KC_TRNS, KC_SYSTEM_SLEEP, RGB_MODE_RAINBOW, RGB_HUI, KC_TRNS, KC_TRNS),
};

// Follwoing is example settings block, it's YAML all the way. You can replace keycap
// with a custom text, or change background color. Regular expressions are also
// YAML feature.

/*---

keycaps:
- match: KC_Q
  text: 🐵👍
  bg: red
- match: !!js/regexp /^KC_\\d+/
  bg: "#00ff00"
  
---*/

`.trim(),
};
