export const LANGS = {
    ChooseKeyboardLayout: "Choose a keyboard...",
    ChooseReferenceMapping: "Language...",
    ChooseReferenceKeyboard: "Choose a reference keyboard...",
    ChooseKeyboard: "Choose keyboard...",
    FinnishStandardKeyboard: "Finnish keyboard",
    UkKeyboard: "UK keyboard",
    Ansi104: "ANSI-104",
    Iso105: "ISO-105",
    Ergodox: "Ergodox",
    KeymapsPlaceholder: "KEYMAP configuration in the C file",
    LayoutInput: "Type the C code of the selected key here...",
    KeyboardLayers: "Keyboard layers",
    Add: "Add",
    Remove: "Remove",
    MyLayoutIsMissing: "Where is keyboard...?",
    MyReferenceKeyboardIsMissing: "Where is keyboard...?",
    MyLanguageMapIsMissing: "Where is language...?",
    LayoutNotSelectedError: "Layout must be chosen for KEYMAPS to work",
    CtrlSingleLetter: "C",
    ShiftSingleLetter: "S",
    AltSingleLetter: "A",
    WinSingleLetter: "W",
};
