export const LANGS = {
    ChooseKeyboardLayout: "Choose a keyboard...",
    ChooseReferenceMapping: "Language...",
    ChooseReferenceKeyboard: "Choose a reference keyboard...",
    ChooseKeyboard: "Choose keyboard...",
    FinnishStandardKeyboard: "Finnish keyboard",
    UkKeyboard: "UK keyboard",
    Ansi104: "ANSI-104",
    Iso105: "ISO-105",
    Ergodox: "Ergodox",
    KeymapsPlaceholder: "Insert contents of keymap.c here...",
    LayoutInput: "Type the code of the selected key here...",
    KeyboardLayers: "Keyboard layers",
    Add: "Add",
    Remove: "Remove",
    MyLayoutIsMissing: "Where is keyboard...?",
    MyReferenceKeyboardIsMissing: "Where is keyboard...?",
    MyLanguageMapIsMissing: "Where is language...?",
    LayoutNotSelectedError: "Layout must be chosen for KEYMAPS to work",
    NoErrors: "No Errors",

    CtrlSingleLetter: "C",
    ShiftSingleLetter: "S",
    AltSingleLetter: "A",
    WinSingleLetter: "W",

    CtrlThreeLetter: "Ctl",
    ShiftThreeLetter: "Sft",
    AltThreeLetter: "Alt",
    WinThreeLetter: "Win",

    Hyper: "Hyper",
    Meh: "Meh",
};
